baseurl = "https://www.devany.net/"
#baseurl = "https://localhost"
languageCode = "en"
title = "devAny"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "shohey1226"
	description = ""
	copyright = "@shohey1226"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/shohey1226/devAnyDoc"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/custom.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "white"
    	accent  = "cyan"

    [params.font]
    	text = "Source Sans Pro"


[social]
	twitter = "shohey1226"
	github  = ""
	email   = ""


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Secure connection"
	url    = "secure-connection/"
	weight = 15	

[[menu.main]]
	name   = "How to use"
	url    = "how-to-use/"
	weight = 20	

[[menu.main]]
	name   = "Privacy"
	url    = "privacy/"
	weight = 25

[[menu.main]]
	name   = "Terms & Conditions"
	url    = "terms/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
